# Generated by Django 4.1.6 on 2023-02-20 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('pages', models.PositiveIntegerField()),
                ('ratings', models.PositiveIntegerField()),
            ],
        ),
    ]
